system:
  timezone: US/Eastern
  base_path: examples
  routes_path: examples/config

logging:
  destination: \Neuron\Log\Destination\File
  format: \Neuron\Log\Format\PlainText
  file: test.log
  level: debug

cache:
  enabled: true
  storage: file
  path: cache/views
  ttl: 3600
  html: true
  markdown: true
  json: false
  xml: false
  # Garbage collection settings (optional, defaults shown)
  # gc_probability: 0.01  # 1% chance to run GC on cache write
  # gc_divisor: 100      # Used with probability for fine-tuning

views:
  path: views

site:
  name: 'Neuron'
  url: 'https://neuron.example.com'
  description: 'A modern blogging platform built with Neuron.'

blog:
  path: 'blog'
  title: 'Neuron Blog'
